version: "3.8"

services:
  score-db:
    image: postgres:latest
    container_name: scoring-db-container
    ports:
      - "9880:5432"
    environment:
      POSTGRES_USER: scoring
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: scoring
    volumes:
      - contact:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4
    container_name: pgadmin-container-scoring
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: scoring
      PGADMIN_DEFAULT_PASSWORD: 12345

volumes:
  contact: