spring:
  application:
    name: scoring

server:
  port: 8089


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8765/eureka